name: movie_info_provider
description: A starting point for Dart libraries or applications.
version: 1.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  domain:
    path: ../domain
  dio: ^3.0.9
  retrofit: ^1.3.4
  json_annotation: ^3.0.1
  logging: ^0.11.4

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  mockito: ^4.1.1
  retrofit_generator: ^1.3.7+4
  json_serializable: ^3.3.0
  build_runner: ^1.10.0

