name: domain
description: A starting point for Dart libraries or applications.
version: 1.0.1

environment:
  sdk: '>=2.7.0 <3.0.0'

#dependency_overrides:
#  analyzer: '0.39.14'

dependencies:
  json_annotation: ^3.0.1

dev_dependencies:
  json_serializable: ^3.3.0
  build_runner: ^1.10.1
  effective_dart: ^1.1.2
  test: ^1.6.0
