name: domain
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependency_overrides:
  analyzer: '0.39.14'

dependencies:
  json_annotation: ^3.0.0

dev_dependencies:
  json_serializable: ^3.2.0
  build_runner: ^1.10.0
  effective_dart: ^1.1.2
  test: ^1.6.0
